### ISSUE TITLE
NoContent should be supported

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#16]
$ pulp build
    * Building project in /home/user/src/app/app-client-web/frontend
    ...
    Compiling ServerAPI
    Error found:
    in module ServerAPI
    at /home/user/src/app/app-client-web/frontend/src/ServerAPI.purs line 17, column 1 - line 17, column 44
    
      Unknown module Servant.API.ContentTypes
    
    
    See https://github.com/purescript/purescript/wiki/Error-Code-UnknownName for more information, or to contribute content related to this error.
     
    
    * ERROR: Subcommand terminated with exit code 1

`/home/user/src/app/app-client-web/frontend/src/ServerAPI.purs` line 17:

    import Servant.API.ContentTypes (NoContent)

**Comment by eskimor** [comment]
Unfortunately I am currently super busy - so if anyone wants to take a look at this - I'd love a PR!

**Comment by legrostdg** [comment]
Any news on this?

I tried to think about it. I first tried this:

    noContentBridge :: BridgePart
    noContentBridge = typeName ^== "NoContent" >> return psUnit

But, as Servant returns `""` for `NoContent`, the JSON parser will failed with this error (which is right, as `""` is not valid JSON):

    JSON.parse:     unexpected end of data at line 1 column 1 of the JSON data, source: ''"

So I guess we should handle this manually...

**Comment by eskimor** [comment]
Yeah, this should definitely handled in servant-purescript.

**Comment by eskimor** [comment]
I think the easiest way to handle this is to special case Unit and not parse the body in this case. Would this solve your problem?

**Comment by eskimor** [comment]
If I get this correctly `NoContent` is the content type like `JSON`, so you still have to provide a type - which would probably be `()` - right? So if if hande `Unit` in servant-purescript to simply ignore the response body and deliver `unit` this should work - right?

**Comment by eskimor** [comment]
Can you try, whether [this](https://github.com/eskimor/servant-purescript/tree/NoContent) fixes your problem?

**Comment by legrostdg** [comment]
@eskimor it does fix the problem, thanks! I'll submit a pull request to add NoContent to purescript-bridge.
