### ISSUE TITLE
central-counter example does not build

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#17]
I can't manage building the `central-counter` example:

     $ pulp build
    * Building project in /tmp/central-counter/frontend
    Error 1 of 4:
    
      at /tmp/central-counter/frontend/bower_components/purescript-functors/src/Data/Functor/Product.purs line 30, column 1 - line 30, column 1
    
        Unable to parse module:
        unexpected type wildcard
    
    
      See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
      or to contribute content related to this error.
    
    Error 2 of 4:
    
      at /tmp/central-counter/frontend/bower_components/purescript-functors/src/Data/Functor/Coproduct.purs line 41, column 1 - line 41, column 1
    
        Unable to parse module:
        unexpected type wildcard
    
    
      See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
      or to contribute content related to this error.
    
    Error 3 of 4:
    
      at /tmp/central-counter/frontend/bower_components/purescript-functors/src/Data/Functor/Compose.purs line 26, column 1 - line 26, column 1
    
        Unable to parse module:
        unexpected type wildcard
    
    
      See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
      or to contribute content related to this error.
    
    Error 4 of 4:
    
      at /tmp/central-counter/frontend/bower_components/purescript-newtype/src/Data/Newtype.purs line 26, column 19 - line 26, column 19
    
        Unable to parse module:
        unexpected |
        expecting no indentation or end of input
    
    
      See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
      or to contribute content related to this error.
    
    
    * ERROR: Subcommand terminated with exit code 1

**Comment by eskimor** [comment]
I am guessing you are using purescript-0.10? Currently we still only support 0.9. Sorry about that.

**Comment by legrostdg** [comment]
I'm using psc 0.9.3:

    $ pulp --version
    Pulp version 10.0.0
    psc version 0.9.3 using /home/user/.local/share/npm/bin/psc

**Comment by legrostdg** [comment]
$ stack list-dependencies  | grep -i servant-purescript
    servant-purescript 0.3.1.5

I'm investigating...

**Comment by legrostdg** [comment]
Same problem, after recompiling with servant-purescript-0.6.0.0, regenerating the purescript code, and running `pulp build` again.

**Comment by eskimor** [comment]
please just do:
```
rm -Rf bower_components/purescript-functors
rm -Rf bower_components/purescript-newtype
```

This should help.

**Comment by legrostdg** [comment]
It worked! Thanks!
