### ISSUE TITLE
psc-0.10 support

### ISSUE THREAD

**Issue by eskimor** [eskimor/servant-purescript#20]
Does the generated code compile with psc-0.10 and updated deps?

**Comment by legrostdg** [comment]
It does for me!

**Comment by eskimor** [comment]
thanks!

**Comment by eskimor** [comment]
ok, bower.json needs dependency dumps, than we can push a psc-0.10 release.

**Comment by andremarianiello** [comment]
For me, the latest version of purescript-subscriber breaks with newer versions of its dependencies. I had to modify purescript-subscriber to get it to build

**Comment by legrostdg** [comment]
Note that `purescript-subscriber` is also used in the `central-counter` example.

**Comment by andremarianiello** [comment]
Yes, sorry, I should have specified that I was talking about the example code.

**Comment by jmatsushita** [comment]
@andremarianiello could you push the updates you did to `purescript-subscriber` on a fork maybe?

**Comment by andremarianiello** [comment]
@jmatsushita All the changes I made are contained in this PR https://github.com/eskimor/purescript-subscriber/issues/7. I don't think I need to push anything.

**Comment by vyorkin** [comment]
Can anybody please tell if it works with `purs` v0.13? There was some recent activity in the repo so I guess it should!
