### ISSUE TITLE
using remote server: CORS header

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#22]
I'd like to separate the server with my server running the servant API from my purescript client.

I tried to run the server on `http://127.0.0.1:8080`, and a small server providing the index.html/app.js from the client on `http://127.0.0.1:8081`. I'm getting:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8080/movie/get/id/1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I've found `wai-cors` and enabled it on the server side. It appears that the client has to set an `Origin` header: https://github.com/larskuhtz/wai-cors/issues/7 Is-it something servant-purescript should do? Do you have any clue about to fix this?

**Comment by eskimor** [comment]
No this is something the browser should do and does, I have a working nginx config, wait a minute ...

the relevant part:
```
                  location / {
                    proxy_pass http://127.0.0.1:${port};
                    add_header 'Access-Control-Allow-Origin' 'https://${frontend_server}' always;
                    add_header 'Access-Control-Allow-Methods' '*, PUT, DELETE, POST, GET' always;
                    add_header 'Access-Control-Allow-Headers' '*, content-type, authorization' always;
                    add_header 'Access-Control-Allow-Credentials:' true always;
                    if ($request_method = 'OPTIONS') {
                      add_header 'Access-Control-Allow-Origin' 'https://${frontend_server}' always;
                      add_header 'Access-Control-Allow-Methods' '*, PUT, DELETE, POST, GET' always;
                      add_header 'Access-Control-Allow-Headers' '*, content-type, authorization' always;
                      add_header 'Access-Control-Allow-Credentials' true always;
                      # Tell client that this pre-flight info is valid for 20 days
                      add_header 'Access-Control-Max-Age' 1728000 always;
                      add_header 'Content-Type' 'text/plain charset=UTF-8';
                      add_header 'Content-Length' 0;
                      return 204;
                    }
                  }
```

**Comment by eskimor** [comment]
Closing, if you feel this is an error - re-open.

**Comment by legrostdg** [comment]
I'd like to do a desktop webapp, so I can't use nginx to set these headers... Is there an alternative?

**Comment by eskimor** [comment]
Sure, those headers are set by the server. You can do this in wai directly for example with some middleware.
