### ISSUE TITLE
Trouble compiling generated code with pulp build

### ISSUE THREAD

**Issue by nlander** [eskimor/servant-purescript#23]
I am trying to compile the generated code with `pulp build` and so far I have gotten three compile errors.
![generated_purescript_error_1](https://cloud.githubusercontent.com/assets/5264410/22806230/1b11a710-eeef-11e6-94b7-d5d296c0f2b6.png)
That error was easy to fix:
![generated_purescript_error_1_fix](https://cloud.githubusercontent.com/assets/5264410/22806253/2f71d3ec-eeef-11e6-9763-d97d1edec052.png)
The second error was:
![generated_purescript_error_2](https://cloud.githubusercontent.com/assets/5264410/22806262/42fa70ea-eeef-11e6-97e7-1ed054ec888b.png)
It was also easy to fix:
![generated_purescript_error_2_fix](https://cloud.githubusercontent.com/assets/5264410/22806293/5b48d0a6-eeef-11e6-96d3-4946792acfaf.png)
The third error I got has me and my coworkers a bit stumped:
![generated_purescript_error_3a](https://cloud.githubusercontent.com/assets/5264410/22806322/888b994a-eeef-11e6-926b-67d63d5d4097.png)
![generated_purescript_error_3b](https://cloud.githubusercontent.com/assets/5264410/22806330/90dce5f4-eeef-11e6-9526-50bdd712e6c4.png)
![generated_purescript_error_3c](https://cloud.githubusercontent.com/assets/5264410/22806335/99ffe104-eeef-11e6-9fc6-bb7928b07c89.png)
Any help understanding what is going on here would be appreciated.

**Comment by eskimor** [comment]
What servant-purescript version are you using?

**Comment by legrostdg** [comment]
@nlander Could you use text instead of images? It would help visually impaired people.

**Comment by nlander** [comment]
I am using the version that comes with stackage lts 7.19, which is 0.3.1.5

**Comment by nlander** [comment]
@legrostdg here is the third compile error in text form:
    Error found:
    in module ServerAPI
    at /home/nlander/clearnexus-chrome-extension/src/Client/ServerAPI.purs line 28, column 1 - line 45, column 31

     Could not match type

       Error

      with type

        AjaxError


   while solving type class constraint

      Control.Monad.Error.Class.MonadError AjaxError
                                           (Aff t3)

    while checking that expression \email ->
                                     \access_token ->
	   			   (bind ask) (\$2 ->
		   		                 ...
			    		      )
      has type forall eff m.
                 ( MonadReader (SPSettings_ SPParams_) m
	         , MonadError Error m
	        , MonadAff
	            ( ajax :: AJAX
		     | eff
		     )
		     m
	        ) => UriEmail -> Token -> m EmailProperties    
    while applying a function (bind (#dict Bind t0)) (ask (#dict MonadAsk t3 t4))
     of type (t0 -> t1 t2) -> t1 t2
      to argument \$2 ->
                case $2 of
	        	  spOpts_' -> let
		                   ...
			          in ...
   in value declaration getApiEmailByEmail

    where t1 is an unknown type
         t2 is an unknown type
         t0 is an unknown type
          t3 is an unknown type`

**Comment by legrostdg** [comment]
@nlander "man github-markdown-syntax". You can prefix everything with 4 spaces, to have a nice looking code block.

**Comment by legrostdg** [comment]
update your version of `servant-purescript`, 0.3.1.5 is outdated.

**Comment by nlander** [comment]
I updated to servant-purescript-0.6.0.0 and everything built fine.  Thanks!
