### ISSUE TITLE
purescript 0.11 support

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#27]
`servant-purescript` seems to be incompatible with purescript 0.11.

When building servant-purescript generated project, I get this error: 

    Error found:
    at src/ServerAPI.purs line 28, column 1 - line 28, column 1
    
      Unable to parse module:
      unexpected comma in constraints.
    
    Class constraints in type annotations can no longer be grouped in parentheses.
    Each constraint should now be separated by `=>`, for example:
        `(Applicative f, Semigroup a) => a -> f a -> f a`
      would now be written as:
        `Applicative f => Semigroup a => a -> f a -> f a`.
    
      expecting indentation past column 1, (, qualifier, proper name, operator or ->
    
    
    See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
    or to contribute content related to this error.
    
    
    * ERROR: Subcommand terminated with exit code 1

And line 28 contains 

    postMovieSearch :: forall eff m.
                       (MonadAsk (SPSettings_ SPParams_) m, MonadError AjaxError m, MonadAff ( ajax :: AJAX | eff) m)
                       => MovieSearch -> m (Array ResponseSimpleMovie)

**Comment by eskimor** [comment]
Ok the fix seems obvious. Unfortunately, I am pretty busy right now, so I would be happy about a PR.
