### ISSUE TITLE
fails with APIs with strings containing hiphens (servant-foreign-0.10 change)

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#31]
`servant-foreign 0.10` avoids JavaScript specific mangling to the names. So, the code generated by `servant-purescript` will fail for APIs containing strings with hiphens.

**Comment by eskimor** [comment]
I am afraid, I don't fully understand the issue. Could you elaborate a bit?

**Comment by legrostdg** [comment]
if you have "/auto-update GET" in your API, `servant-purescript` used to generate "getAutoupdate", and now generates "getAuto-update", which is not valid. Note that this function name is valid in other languages, that's why the hyphen escaping/removal has been moved to `servant-js`.
We should probably depend on "servant-js" instead of "servant-foreign", or copy the hyphen-escaping/removal logic in `servant-purescript`.

**Comment by eskimor** [comment]
I see. Thank you!
