### ISSUE TITLE
uninstable with stack 2.1.1

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#38]
In one of my projects:

```
$ stack build
Cloning 7b0090a017318ff970db79455c53c60cdb0b1611 from https://github.com/eskimor/servant-purescript.git
Unsupported tarball from /tmp/with-repo-archive14210/foo.tar: File located at "examples/central-counter/frontend/setupPath.sh" is a symbolic link to absolute path /home/robert/projects/gonimo-front/setupPath.sh

**Comment by legrostdg** [comment]
bump?

**Comment by vlatkoB** [comment]
It is related to this [stack issue](https://github.com/commercialhaskell/stack/issues/5004).

**Comment by legrostdg** [comment]
Thanks for the link, which links to this issue https://github.com/commercialhaskell/stack/issues/4913 which directly mentions servant-purescript.

**Comment by eskimor** [comment]
uhm, interesting - that symlink seems weird. I'll check it out.

**Comment by eskimor** [comment]
Does the problem persist with 0.9.0.4?

**Comment by legrostdg** [comment]
0.9.0.4 fixes this issue.

**Comment by eskimor** [comment]
Thanks @legrostdg! Sorry, that it took so long, I completely missed that, due to too many github notifications.

**Comment by legrostdg** [comment]
note that there is https://github.com/eskimor/servant-subscriber/issues/23 now (new github notification :))
