### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by legrostdg** [eskimor/servant-purescript#5]
Could you add servant-purescript to stackage?

Thanks!

**Comment by eskimor** [comment]
Already on the agenda - yeah ;-) Coming soon.

**Comment by eskimor** [comment]
Although don't hold your breath - we are currently super busy, so it could take a while.

**Comment by eskimor** [comment]
To get in stackage master the libraries need to build on ghc-8.0. @epsilonhalbe Maybe you could have a look when you got time. It should not be too hard to make them work.

**Comment by eskimor** [comment]
PR for 7.10 already available: https://github.com/fpco/stackage/pull/1845

**Comment by eskimor** [comment]
PR closed - issue for lts6: https://github.com/fpco/lts-haskell/issues/26

**Comment by eskimor** [comment]
Ok - I made it work with ghc 8 - this also fixed haddocks at least for purescript-bridge.
PR for stackage integration: https://github.com/fpco/stackage/pull/1846

**Comment by eskimor** [comment]
Done: https://www.stackage.org/nightly-2016-09-10/package/servant-purescript-0.3.1.4
